import type { FamilyData } from "./types";

export const demoData: FamilyData = {
  version: 1,
  members: [
    {
      id: "grandfather",
      name: "Rahim Uddin",
      gender: "male",
      birthDate: "1945-03-12",
      spouseIds: ["grandmother"],
      biography: "পরিবারের প্রবীণ সদস্য।",
    },
    {
      id: "grandmother",
      name: "Amena Begum",
      gender: "female",
      birthDate: "1950-07-21",
      spouseIds: ["grandfather"],
    },
    {
      id: "father",
      name: "Kamal Hossain",
      gender: "male",
      birthDate: "1972-01-05",
      fatherId: "grandfather",
      motherId: "grandmother",
      spouseIds: ["mother"],
    },
    {
      id: "mother",
      name: "Shirin Akter",
      gender: "female",
      birthDate: "1976-09-18",
      spouseIds: ["father"],
    },
    {
      id: "uncle",
      name: "Jamal Hossain",
      gender: "male",
      birthDate: "1975-05-30",
      fatherId: "grandfather",
      motherId: "grandmother",
      spouseIds: ["aunt"],
    },
    {
      id: "aunt",
      name: "Nasrin Akter",
      gender: "female",
      birthDate: "1979-11-02",
      spouseIds: ["uncle"],
    },
    {
      id: "me",
      name: "Arif Hossain",
      nickname: "Me",
      gender: "male",
      birthDate: "2000-04-14",
      fatherId: "father",
      motherId: "mother",
      spouseIds: [],
    },
    {
      id: "brother",
      name: "Tanvir Hossain",
      gender: "male",
      birthDate: "2003-08-09",
      fatherId: "father",
      motherId: "mother",
      spouseIds: [],
    },
    {
      id: "sister",
      name: "Mim Hossain",
      gender: "female",
      birthDate: "2006-12-25",
      fatherId: "father",
      motherId: "mother",
      spouseIds: [],
    },
  ],
};
